# Generated by Django 3.1.5 on 2021-01-27 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('dish_type', models.CharField(choices=[('ME', 'Main Entree'), ('SD', 'Side Dish'), ('DT', 'Desert/Treat')], max_length=2)),
                ('cooking_method', models.CharField(choices=[('OB', 'Oven Bake'), ('PF', 'Pan Fry'), ('IP', 'Instant Pot'), ('SC', 'Slow Cooker'), ('DF', 'Deep Fry ')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('prep_instructions', models.CharField(max_length=255)),
                ('alternatives', models.ManyToManyField(related_name='alternatives', to='menu.Ingredient')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='menu.RecipeIngredients', to='menu.Ingredient'),
        ),
    ]
