# Generated by Django 3.1.5 on 2021-01-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20210130_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymembers',
            options={'verbose_name_plural': 'Family Members'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name_plural': 'Recipe Ingredients'},
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='alternatives',
            field=models.ManyToManyField(blank=True, related_name='alternatives', to='menu.Ingredient'),
        ),
    ]
