# Generated by Django 3.1.5 on 2021-02-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20210131_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='(none)', max_length=255),
        ),
    ]
