# Generated by Django 3.1.5 on 2021-02-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
