# Generated by Django 3.1.5 on 2021-01-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='alternatives',
            field=models.ManyToManyField(blank=True, null=True, related_name='alternatives', to='menu.Ingredient'),
        ),
    ]
