# Generated by Django 3.1.5 on 2021-01-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210127_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='prep_instructions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
