# Generated by Django 3.1.5 on 2021-01-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='meal_time',
            field=models.CharField(choices=[('BK', 'Breakfast'), ('LU', 'Lunch'), ('SU', 'Supper')], default='SU', max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('ME', 'Main Entree'), ('SD', 'Side Dish'), ('DT', 'Desert/Treat')], default='ME', max_length=2),
        ),
    ]
